/*
 * Devices service
 *
 * Microservice for managing Giò Plants devices
 *
 * API version: 1.0.0
 * Contact: andrea.liut@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package config

type Config struct {
	DeviceServiceConfig *DeviceServiceConfig `json:"device_service"`
}

type DeviceServiceConfig struct {
	Host string `json:"host"`
	Port int32  `json:"port"`
}
