/*
 * Devices service
 *
 * Microservice for managing Giò Plants devices
 *
 * API version: 1.0.0
 * Contact: andrea.liut@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package model

import (
	"fmt"
)

type Device struct {
	ID   string `json:"id,omitempty"`
	Name string `json:"name"`
	Mac  string `json:"mac"`
	Room string `json:"room"`
}

func (device *Device) Validate() (bool, error) {
	if device.Name == "" {
		return false, fmt.Errorf("invalid name")
	}

	if device.Mac == "" {
		return false, fmt.Errorf("invalid mac")
	}

	if device.Room == "" {
		return false, fmt.Errorf("invalid room")
	}

	return true, nil
}

type Reading struct {
	ID                string `json:"id,omitempty"`
	Name              string `json:"name"`
	Value             string `json:"value"`
	Unit              string `json:"unit"`
	CreationTimestamp string `json:"creation_timestamp"`
}
